// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACU4NT3_wzGgi1hemuiKZOuC5jRecdyU',
    appId: '1:133342272401:android:23fd1e5e1b3ea5d7d65830',
    messagingSenderId: '133342272401',
    projectId: 'spinwin-b58be',
    storageBucket: 'spinwin-b58be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzGlwxdZoenXCHeXTjeKUZoyr7YN7jnRY',
    appId: '1:133342272401:ios:41149b6143511c46d65830',
    messagingSenderId: '133342272401',
    projectId: 'spinwin-b58be',
    storageBucket: 'spinwin-b58be.appspot.com',
    iosBundleId: 'com.example.spinWin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzGlwxdZoenXCHeXTjeKUZoyr7YN7jnRY',
    appId: '1:133342272401:ios:5e6b1d8c7cd98f62d65830',
    messagingSenderId: '133342272401',
    projectId: 'spinwin-b58be',
    storageBucket: 'spinwin-b58be.appspot.com',
    iosBundleId: 'com.example.spinWin.RunnerTests',
  );
}
